### ISSUE TITLE
Connect Marzban Node to Multiple Panels UDP Problem

### ISSUE THREAD

**Issue by RelaxStation** [Gozargah/Marzban-node#72]
Hi
If I connect the Marzban Node to Multiple Panels with Solution 2: Port Mapping, the UDP is not working for Shadowsocks or KCP
https://gozargah.github.io/marzban/en/docs/marzban-node
What is the solution?
```
services:
  marzban-node-1:
    image: gozargah/marzban-node:latest
    restart: always
    environment:
      SSL_CLIENT_CERT_FILE: "/var/lib/marzban-node/ssl_client_cert_1.pem"
      SERVICE_PROTOCOL: "rest"

    volumes:
      - /var/lib/marzban-node:/var/lib/marzban-node
      - /var/lib/marzban:/var/lib/marzban
      - /var/lib/marzban/assets:/usr/local/share/xray

    ports:
      - 11001:62050
      - 13001:62051
      - 8443:8443
      - 1080:1080


  marzban-node-2:
    image: gozargah/marzban-node:latest
    restart: always
    environment:
      SSL_CLIENT_CERT_FILE: "/var/lib/marzban-node/ssl_client_cert_2.pem"
      SERVICE_PROTOCOL: "rest"

    volumes:
      - /var/lib/marzban-node:/var/lib/marzban-node
      - /var/lib/marzban:/var/lib/marzban
      - /var/lib/marzban/assets:/usr/local/share/xray

    ports:
      - 11008:62050
      - 13008:62051
      - 2096:2096
      - 443:443
```

I also tried
```
    ports:
      - 11001:62050
      - 13001:62051
      - "1080:1080/tcp"
      - "1080:1080/udp"
      
```
but nothing changed
